#include "loaders.hpp"
#include "msplat.hpp"
#include <fstream>
#include <algorithm>
#include <numeric>
#include <cmath>
#include <cstring>
#include <cstdint>
#include <sstream>

static const double C0 = 0.28209479177387814;

static bool hasLodStats(const GaussianLodStats *stats) {
    return stats && stats->visCounts && stats->xysGradNorm && stats->max2DSize;
}

static std::vector<size_t> rankedGaussianIndices(GaussianParams &p, const GaussianLodStats *stats = nullptr) {
    int64_t N = p.means.size(0);
    const float *sp = p.scales.data<float>();
    const float *op = p.opacities.data<float>();
    bool useStats = hasLodStats(stats);

    std::vector<float> scores(N);
    for (int64_t i = 0; i < N; i++) {
        float s = std::exp(sp[i*3]) + std::exp(sp[i*3+1]) + std::exp(sp[i*3+2]);
        if (p.keepCrs) s /= p.scale;
        float score = s / (1.0f + std::exp(-op[i]));
        if (useStats) {
            float vis = stats->visCounts[i];
            if (vis > 0.0f) {
                float refineWeight = stats->xysGradNorm[i];
                float screen = std::max(0.0f, stats->max2DSize[i]);
                float sensitivity = std::log1p(vis) * (std::sqrt(std::max(0.0f, refineWeight)) + screen);
                score *= 1.0f + sensitivity;
            }
        }
        scores[i] = score;
    }

    std::vector<size_t> idx(N);
    std::iota(idx.begin(), idx.end(), 0);
    std::sort(idx.begin(), idx.end(), [&](size_t a, size_t b) {
        if (scores[a] == scores[b]) return a < b;
        return scores[a] > scores[b];
    });
    return idx;
}

static void saveGaussianPlyWithOrder(const std::string &path, GaussianParams &p, int step, const std::vector<size_t> *order, int64_t count, const char *lodScoreSource = nullptr) {
    msplat_gpu_sync();

    std::ofstream o(path, std::ios::binary);
    int64_t N = p.means.size(0);
    if (count < 0 || count > N) count = N;
    int numDc = (int)p.featuresDc.size(1);
    int frBases = (int)p.featuresRest.size(-2);
    int numFr = frBases * 3;

    o << "ply\nformat binary_little_endian 1.0\n";
    o << "comment msplat v" << step << "\n";
    o << "comment Generated by msplat at iteration " << step << "\n";
    o << "comment SplatRenderMode: " << (p.renderMip ? "mip" : "default") << "\n";
    if (count != N) o << "comment msplat_lod_source_count " << N << "\n";
    if (lodScoreSource) o << "comment msplat_lod_score_source " << lodScoreSource << "\n";
    o << "element vertex " << count << "\n";
    o << "property float x\nproperty float y\nproperty float z\n";
    o << "property float nx\nproperty float ny\nproperty float nz\n";
    for (int i = 0; i < numDc; i++) o << "property float f_dc_" << i << "\n";
    for (int i = 0; i < numFr; i++) o << "property float f_rest_" << i << "\n";
    o << "property float opacity\n";
    o << "property float scale_0\nproperty float scale_1\nproperty float scale_2\n";
    o << "property float rot_0\nproperty float rot_1\nproperty float rot_2\nproperty float rot_3\n";
    o << "end_header\n";

    int floatsPerRow = 3 + 3 + numDc + numFr + 1 + 3 + 4;
    std::vector<float> row(floatsPerRow);
    const float *mp = p.means.data<float>(), *sp = p.scales.data<float>(), *qp = p.quats.data<float>();
    const float *dp = p.featuresDc.data<float>(), *op = p.opacities.data<float>();
    const float *frp = p.featuresRest.data<float>();

    for (int64_t ii = 0; ii < count; ii++) {
        size_t i = order ? (*order)[ii] : (size_t)ii;
        int c = 0;
        for (int j = 0; j < 3; j++)
            row[c++] = p.keepCrs ? (mp[i*3+j] / p.scale + p.translation[j]) : mp[i*3+j];
        row[c++] = 0; row[c++] = 0; row[c++] = 0; // normals
        for (int j = 0; j < numDc; j++) row[c++] = dp[i*numDc+j];
        // Transpose [frBases, 3] → [3, frBases] for PLY convention
        for (int ch = 0; ch < 3; ch++)
            for (int b = 0; b < frBases; b++)
                row[c++] = frp[i*frBases*3 + b*3 + ch];
        row[c++] = op[i];
        for (int j = 0; j < 3; j++)
            row[c++] = p.keepCrs ? std::log(std::exp(sp[i*3+j]) / p.scale) : sp[i*3+j];
        for (int j = 0; j < 4; j++) row[c++] = qp[i*4+j];

        o.write(reinterpret_cast<const char*>(row.data()), floatsPerRow * sizeof(float));
    }
}

void saveGaussianPly(const std::string &path, GaussianParams &p, int step) {
    saveGaussianPlyWithOrder(path, p, step, nullptr, p.means.size(0));
}

void saveGaussianLodPly(const std::string &path, GaussianParams &p, int step, int64_t targetCount,
                        const GaussianLodStats *stats) {
    int64_t N = p.means.size(0);
    targetCount = std::clamp<int64_t>(targetCount, 1, N);
    bool useStats = hasLodStats(stats);
    std::vector<size_t> order = rankedGaussianIndices(p, stats);
    saveGaussianPlyWithOrder(path, p, step, &order, targetCount,
                             useStats ? "training-stats" : "static-size-opacity");
}

LoadedGaussians decimateGaussians(GaussianParams &p, int64_t targetCount,
                                  const GaussianLodStats *stats) {
    msplat_gpu_sync();

    int64_t N = p.means.size(0);
    targetCount = std::clamp<int64_t>(targetCount, 1, N);
    std::vector<size_t> order = rankedGaussianIndices(p, stats);

    int frBases = (int)p.featuresRest.size(-2);
    int64_t frStride = (int64_t)frBases * 3;
    LoadedGaussians out{
        gpu_empty({targetCount, 3}, DType::Float32),
        gpu_empty({targetCount, 3}, DType::Float32),
        gpu_empty({targetCount, 4}, DType::Float32),
        gpu_empty({targetCount, 3}, DType::Float32),
        gpu_empty({targetCount, frBases, 3}, DType::Float32),
        gpu_empty({targetCount, 1}, DType::Float32),
        0,
        false,
        p.renderMip
    };

    const float *mp = p.means.data<float>();
    const float *sp = p.scales.data<float>();
    const float *qp = p.quats.data<float>();
    const float *dp = p.featuresDc.data<float>();
    const float *frp = p.featuresRest.data<float>();
    const float *op = p.opacities.data<float>();

    float *omp = out.means.data<float>();
    float *osp = out.scales.data<float>();
    float *oqp = out.quats.data<float>();
    float *odp = out.featuresDc.data<float>();
    float *ofrp = out.featuresRest.data<float>();
    float *oop = out.opacities.data<float>();

    for (int64_t dst = 0; dst < targetCount; dst++) {
        size_t src = order[dst];
        memcpy(&omp[dst * 3], &mp[src * 3], 3 * sizeof(float));
        memcpy(&osp[dst * 3], &sp[src * 3], 3 * sizeof(float));
        memcpy(&oqp[dst * 4], &qp[src * 4], 4 * sizeof(float));
        memcpy(&odp[dst * 3], &dp[src * 3], 3 * sizeof(float));
        memcpy(&ofrp[dst * frStride], &frp[src * frStride], frStride * sizeof(float));
        oop[dst] = op[src];
    }

    return out;
}

void saveGaussianSplat(const std::string &path, GaussianParams &p) {
    msplat_gpu_sync();

    std::ofstream o(path, std::ios::binary);
    int64_t N = p.means.size(0);
    const float *mp = p.means.data<float>(), *sp = p.scales.data<float>(), *qp = p.quats.data<float>();
    const float *dp = p.featuresDc.data<float>(), *op = p.opacities.data<float>();

    // Sort by size/opacity (largest first)
    std::vector<size_t> idx = rankedGaussianIndices(p);

    for (int64_t ii = 0; ii < N; ii++) {
        size_t i = idx[ii];
        float m[3];
        for (int j = 0; j < 3; j++) m[j] = p.keepCrs ? (mp[i*3+j] / p.scale + p.translation[j]) : mp[i*3+j];
        o.write(reinterpret_cast<const char*>(m), 12);

        float sc[3];
        for (int j = 0; j < 3; j++) sc[j] = p.keepCrs ? (std::exp(sp[i*3+j]) / p.scale) : std::exp(sp[i*3+j]);
        o.write(reinterpret_cast<const char*>(sc), 12);

        uint8_t rgb[3];
        for (int j = 0; j < 3; j++) rgb[j] = (uint8_t)std::clamp(((double)dp[i*3+j] * C0 + 0.5) * 255.0, 0.0, 255.0);
        o.write(reinterpret_cast<const char*>(rgb), 3);

        float sig = 1.0f / (1.0f + std::exp(-op[i]));
        uint8_t a = (uint8_t)std::clamp(sig * 255.0f, 0.0f, 255.0f);
        o.write(reinterpret_cast<const char*>(&a), 1);

        uint8_t q[4];
        for (int j = 0; j < 4; j++) q[j] = (uint8_t)std::clamp(qp[i*4+j] * 128.0f + 128.0f, 0.0f, 255.0f);
        o.write(reinterpret_cast<const char*>(q), 4);
    }
}

struct PlyScalarProperty {
    std::string type;
    std::string name;
};

static size_t plyScalarTypeSize(const std::string &type) {
    if (type == "char" || type == "int8" || type == "uchar" || type == "uint8") return 1;
    if (type == "short" || type == "int16" || type == "ushort" || type == "uint16") return 2;
    if (type == "int" || type == "int32" || type == "uint" || type == "uint32" || type == "float" || type == "float32") return 4;
    if (type == "double" || type == "float64" || type == "long" || type == "int64" || type == "ulong" || type == "uint64") return 8;
    throw std::runtime_error("Unsupported PLY scalar property type: " + type);
}

static float readPlyScalarAsFloat(std::istream &in, const PlyScalarProperty &prop) {
    float out = 0.0f;
    if (prop.type == "float" || prop.type == "float32") {
        float v;
        in.read(reinterpret_cast<char*>(&v), sizeof(v));
        out = v;
    } else if (prop.type == "double" || prop.type == "float64") {
        double v;
        in.read(reinterpret_cast<char*>(&v), sizeof(v));
        out = (float)v;
    } else if (prop.type == "char" || prop.type == "int8") {
        int8_t v;
        in.read(reinterpret_cast<char*>(&v), sizeof(v));
        out = (float)v;
    } else if (prop.type == "uchar" || prop.type == "uint8") {
        uint8_t v;
        in.read(reinterpret_cast<char*>(&v), sizeof(v));
        out = (float)v;
    } else if (prop.type == "short" || prop.type == "int16") {
        int16_t v;
        in.read(reinterpret_cast<char*>(&v), sizeof(v));
        out = (float)v;
    } else if (prop.type == "ushort" || prop.type == "uint16") {
        uint16_t v;
        in.read(reinterpret_cast<char*>(&v), sizeof(v));
        out = (float)v;
    } else if (prop.type == "int" || prop.type == "int32") {
        int32_t v;
        in.read(reinterpret_cast<char*>(&v), sizeof(v));
        out = (float)v;
    } else if (prop.type == "uint" || prop.type == "uint32") {
        uint32_t v;
        in.read(reinterpret_cast<char*>(&v), sizeof(v));
        out = (float)v;
    } else if (prop.type == "long" || prop.type == "int64") {
        int64_t v;
        in.read(reinterpret_cast<char*>(&v), sizeof(v));
        out = (float)v;
    } else if (prop.type == "ulong" || prop.type == "uint64") {
        uint64_t v;
        in.read(reinterpret_cast<char*>(&v), sizeof(v));
        out = (float)v;
    } else {
        std::vector<char> skip(plyScalarTypeSize(prop.type));
        in.read(skip.data(), (std::streamsize)skip.size());
    }
    if (!in) throw std::runtime_error("Unexpected EOF while reading PLY property: " + prop.name);
    return out;
}

static bool parseIndexedProperty(const std::string &name, const std::string &prefix, int &index) {
    if (name.rfind(prefix, 0) != 0) return false;
    index = std::stoi(name.substr(prefix.size()));
    return true;
}

LoadedGaussians loadGaussianPly(const std::string &path, float scale, const float translation[3],
                                bool keepCrs, int subsampleStep) {
    msplat_gpu_sync();
    subsampleStep = std::max(subsampleStep, 1);

    std::ifstream f(path, std::ios::binary);
    if (!f.is_open()) throw std::runtime_error("Cannot open PLY file: " + path);

    // Parse header
    std::string line;
    int numPoints = 0, step = 0;
    int numDc = 0, numFr = 0;
    bool hasRenderMip = false;
    bool renderMip = false;
    bool hasRgbColor = false;
    bool inVertex = false;
    std::vector<PlyScalarProperty> vertexProperties;

    std::getline(f, line); // "ply"
    if (line.find("ply") == std::string::npos) throw std::runtime_error("Not a PLY file: " + path);
    std::getline(f, line); // "format binary_little_endian 1.0"
    if (line.find("format binary_little_endian") == std::string::npos)
        throw std::runtime_error("Only binary_little_endian PLY files are supported: " + path);

    while (std::getline(f, line)) {
        if (line == "end_header") break;

        const std::string iterPrefix = "comment Generated by msplat at iteration ";
        if (line.rfind(iterPrefix, 0) == 0)
            step = std::stoi(line.substr(iterPrefix.length()));

        const std::string compactIterPrefix = "comment msplat v";
        if (line.rfind(compactIterPrefix, 0) == 0)
            step = std::stoi(line.substr(compactIterPrefix.length()));

        const std::string renderModePrefix = "comment SplatRenderMode: ";
        if (line.rfind(renderModePrefix, 0) == 0) {
            std::string mode = line.substr(renderModePrefix.length());
            std::transform(mode.begin(), mode.end(), mode.begin(),
                           [](unsigned char c) { return (char)std::tolower(c); });
            hasRenderMip = mode == "mip" || mode == "default";
            renderMip = mode == "mip";
        }

        const std::string vertexPrefix = "element vertex ";
        if (line.rfind(vertexPrefix, 0) == 0) {
            numPoints = std::stoi(line.substr(vertexPrefix.length()));
            inVertex = true;
            continue;
        }

        if (line.rfind("element ", 0) == 0) {
            inVertex = false;
            continue;
        }

        if (inVertex && line.rfind("property ", 0) == 0) {
            std::istringstream iss(line);
            std::string keyword, type, name;
            iss >> keyword >> type;
            if (type == "list")
                throw std::runtime_error("List properties in PLY vertex elements are not supported: " + path);
            iss >> name;
            plyScalarTypeSize(type);
            vertexProperties.push_back({type, name});

            int index = 0;
            if (parseIndexedProperty(name, "f_dc_", index)) numDc = std::max(numDc, index + 1);
            if (parseIndexedProperty(name, "f_rest_", index)) numFr = std::max(numFr, index + 1);
            if (name == "red" || name == "green" || name == "blue"
                || name == "r" || name == "g" || name == "b") {
                hasRgbColor = true;
            }
        }
    }

    if (numPoints == 0) throw std::runtime_error("PLY has no vertices");
    if (vertexProperties.empty()) throw std::runtime_error("PLY has no vertex properties: " + path);
    if (numDc == 0 && hasRgbColor) numDc = 3;
    int frBases = numFr / 3;

    const int selectedPoints = (numPoints + subsampleStep - 1) / subsampleStep;

    // Read rows by property name. Brush and common INRIA Gaussian PLYs do not
    // guarantee the same property order as msplat exports.
    std::vector<float> meansRaw(selectedPoints * 3);
    std::vector<float> dcRaw(selectedPoints * numDc);
    std::vector<float> frRaw(selectedPoints * numFr);
    std::vector<float> opRaw(selectedPoints);
    std::vector<float> scRaw(selectedPoints * 3);
    std::vector<float> qtRaw(selectedPoints * 4);

    int selected = 0;
    for (int i = 0; i < numPoints; i++) {
        const bool keep = i % subsampleStep == 0;
        if (keep) qtRaw[selected*4] = 1.0f;
        float rgb[3] = {};
        bool hasRgb[3] = {};
        for (const PlyScalarProperty &prop : vertexProperties) {
            float value = readPlyScalarAsFloat(f, prop);
            if (!keep) continue;

            int index = 0;
            if (prop.name == "x") meansRaw[selected*3] = value;
            else if (prop.name == "y") meansRaw[selected*3+1] = value;
            else if (prop.name == "z") meansRaw[selected*3+2] = value;
            else if (prop.name == "opacity") opRaw[selected] = value;
            else if (prop.name == "scale_0") scRaw[selected*3] = value;
            else if (prop.name == "scale_1") scRaw[selected*3+1] = value;
            else if (prop.name == "scale_2") scRaw[selected*3+2] = value;
            else if (prop.name == "rot_0") qtRaw[selected*4] = value;
            else if (prop.name == "rot_1") qtRaw[selected*4+1] = value;
            else if (prop.name == "rot_2") qtRaw[selected*4+2] = value;
            else if (prop.name == "rot_3") qtRaw[selected*4+3] = value;
            else if (parseIndexedProperty(prop.name, "f_dc_", index) && index < numDc) dcRaw[selected*numDc + index] = value;
            else if (parseIndexedProperty(prop.name, "f_rest_", index) && index < numFr) frRaw[selected*numFr + index] = value;
            else if (prop.name == "red" || prop.name == "r") { rgb[0] = value; hasRgb[0] = true; }
            else if (prop.name == "green" || prop.name == "g") { rgb[1] = value; hasRgb[1] = true; }
            else if (prop.name == "blue" || prop.name == "b") { rgb[2] = value; hasRgb[2] = true; }
        }
        if (keep && hasRgb[0] && hasRgb[1] && hasRgb[2] && numDc >= 3) {
            for (int c = 0; c < 3; c++) {
                float channel = rgb[c] > 1.0f ? rgb[c] / 255.0f : rgb[c];
                dcRaw[selected*numDc + c] = (std::clamp(channel, 0.0f, 1.0f) - 0.5f) / (float)C0;
            }
        }
        if (keep) selected++;
    }

    // CRS transform
    if (keepCrs) {
        for (int i = 0; i < selectedPoints; i++)
            for (int j = 0; j < 3; j++)
                meansRaw[i*3+j] = (meansRaw[i*3+j] - translation[j]) * scale;
        for (int i = 0; i < selectedPoints * 3; i++)
            scRaw[i] = std::log(scale * std::exp(scRaw[i]));
    }

    // Upload to GPU
    LoadedGaussians g;
    g.step = step;
    g.hasRenderMip = hasRenderMip;
    g.renderMip = renderMip;
    auto upload = [](std::vector<int64_t> shape, const float *src, size_t bytes) {
        MTensor t = gpu_empty(shape, DType::Float32);
        memcpy(t.data_ptr(), src, bytes);
        return t;
    };
    g.means = upload({(int64_t)selectedPoints, 3}, meansRaw.data(), meansRaw.size() * 4);
    g.featuresDc = upload({(int64_t)selectedPoints, (int64_t)numDc}, dcRaw.data(), dcRaw.size() * 4);
    g.opacities = upload({(int64_t)selectedPoints, 1}, opRaw.data(), opRaw.size() * 4);
    g.scales = upload({(int64_t)selectedPoints, 3}, scRaw.data(), scRaw.size() * 4);
    g.quats = upload({(int64_t)selectedPoints, 4}, qtRaw.data(), qtRaw.size() * 4);

    // Transpose featuresRest: PLY [N, 3, frBases] → internal [N, frBases, 3]
    g.featuresRest = gpu_empty({(int64_t)selectedPoints, (int64_t)frBases, 3}, DType::Float32);
    float *frOut = g.featuresRest.data<float>();
    for (int i = 0; i < selectedPoints; i++)
        for (int ch = 0; ch < 3; ch++)
            for (int b = 0; b < frBases; b++)
                frOut[i*frBases*3 + b*3 + ch] = frRaw[i*numFr + ch*frBases + b];

    // numPoints and step available via returned struct
    return g;
}
